### PR TITLE
Cardapio page & add field nome on create user form

### LINKED ISSUE #56: Sprint 03 - Create Cardapio page

### LINKED ISSUE #57: Sprint 03 - Add name field on user signup

### PR DESCRIPTION
**Pull request by victorc4mpos**

### CODE REVIEW

**Review by Lucas-Angelo — CHANGES_REQUESTED** [review]
Cardapio page needs PR changes https://github.com/Lucas-Angelo/pizzaria/pull/59, it should only be in the cliente user view

**Comment by Lucas-Angelo** [comment]
@777-victor When I click the Pedido option in carpadio, I can't select to buy/ask

**Comment by Lucas-Angelo** [comment]
@777-victor whtf is this? 
image

**Comment by victorc4mpos** [comment]
> @777-victor whtf is this? image

Just to be cute, removed already

**Pull request merged**
