### PR TITLE
feat: add created_at and updated-at fields

### LINKED ISSUE #27: Sprint 02 - Add created_at and updated_at at entities

### PR DESCRIPTION
**Pull request by lucaspere**
## Changes:
- Adds ``createad_at`` and ``updated_at`` for ``Pizza``, ``Pedido`` and ``Usuario``;
- Adds ``createad_at`` and ``updated_at``to ``database.sql``.

### CODE REVIEW

**Comment by Lucas-Angelo** [comment]
@lucaspere as I said before, please put @guizombas to review, not me or Marini. Well, we had already decided that @guizombas needs this feature to do the report (get all)...

**Comment by Lucas-Angelo** [comment]
@lucaspere you did not link to issue #27 when opening this

**Comment by Lucas-Angelo** [comment]
I'm adding @Henrikkee to review as well because he will add this field in the frontend because it was from sprint 01.

**Comment by lucaspere** [comment]
> @lucaspere you did not link to issue #27 when opening this

Oohhhh shit, i forgot it. Thanks

**Review by Henrikkee — CHANGES_REQUESTED** [review]
1-
Missing Sequelize attributes

image
Without them, created_at and updated_at fields has no default values

image
PS: Same thing on Usuario's and Pedido's models

[Sequelize documentation about this](https://sequelize.org/docs/v6/core-concepts/model-basics/#timestamps)

-------------------------------
2-
"TIMESTAMP WITH TIME ZONE" only works on postgres, Sequelize provides its own timezone feature:
[Stackoverflow](https://stackoverflow.com/questions/52096692/change-sequelize-timezone)
[Alura](https://cursos.alura.com.br/forum/topico-sequelize-timezone-166471)

**Comment by lucaspere** [comment]
> 1- Missing Sequelize attributes
> 
> image Without them, created_at and updated_at fields has no default values
> 
> image PS: Same thing on Usuario's and Pedido's models
> 
> [Sequelize documentation about this](https://sequelize.org/docs/v6/core-concepts/model-basics/#timestamps)
> 
> 2- "TIMESTAMP WITH TIME ZONE" only works on postgres, Sequelize provides its own timezone feature: [Stackoverflow](https://stackoverflow.com/questions/52096692/change-sequelize-timezone) [Alura](https://cursos.alura.com.br/forum/topico-sequelize-timezone-166471)

I didn't know that, thanks

**Review by guizombas — APPROVED** [review]

**Review by Lucas-Angelo — APPROVED** [review]

**Pull request merged**
